accounts/urls.py
from django.conf.urls import url

from accounts.views import RegistrationView, LoginView, ControllersView

urlpatterns = [
    url(r'^registration/$', RegistrationView.as_view(), name='registration'),
    url(r'^$', LoginView.as_view(), name='login'),
    url(r'^controllers/$', ControllersView.as_view(), name='controllers'),
]

api/urls.py
from django.conf.urls import url

from api.views import ControllerSettingsView, ControllerStatusView, ControllerResqueView

urlpatterns = [
    url(r'^set', ControllerSettingsView.as_view(), name='controller-settings'),
    url(r'^status', ControllerStatusView.as_view(), name='controller-status'),
    url(r'^resque', ControllerResqueView.as_view(), name='controller-resque'),
]

ihpm5/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from ihpm5 import settings

urlpatterns = [
    url(r'^rest/bin/', include('api.urls', namespace='bin')),
    url(r'^', include('accounts.urls', namespace='accounts')),
]

if settings.ADMIN_ENABLED:
    urlpatterns.append(url(r'^admin/', admin.site.urls),)

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Titillium+Web" rel="stylesheet">
    {% block head %}

    {% endblock head %}

</head>
<body>

<section>
    <header class="text-center">
        <div class="menu-buttons brackets">
            <a href="{% url 'accounts:registration' %}" class="{% if request.path == '/registration/' %}nav-active{% endif %}">Registration</a>
            <a href="{% url 'accounts:controllers' %}" class="{% if request.path == '/controllers/' %}nav-active{% endif %}">Controllers</a>
        </div>
    </header>
</section>

{% block content %}

{% endblock content %}

    <script src="{% static '/js/jquery-latest.js' %}"></script>
    <script src="{% static '/js/jquery.min.js' %}"></script>
    <script src="{% static '/js/bootstrap.min.js' %}"></script>

{% block customscripts %}

{% endblock customscripts %}

</body>